import cv2
import numpy as np
from watermark import extract_zero_watermark

# Load the Secret Key and Encryption Sequence generated by main.py
zero_wm = np.load('zero_watermark.npy')
key_seq = np.load('key_seq.npy') # Ensure main.py saves the key_seq
wm_shape = (32, 32) # Match your logo size

# 1. Simulate an Attack (Adding Noise)
img = cv2.imread('../data/host_image.png', 0)
noise = np.random.normal(0, 20, img.shape).astype(np.uint8)
attacked_img = cv2.add(img, noise)
cv2.imwrite('../data/attacked_image.png', attacked_img)

# 2. Extract from the Ruined Image
recovered = extract_zero_watermark('../data/attacked_image.png', zero_wm, wm_shape, key_seq)
cv2.imwrite('../data/recovered_after_attack.png', (recovered * 255).astype(np.uint8))

print("Robustness test complete. Check data/recovered_after_attack.png")
